name: fitandheal
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  charts_flutter: ^0.9.0
  youtube_player_flutter: ^6.1.1
  font_awesome_flutter: ^8.4.0
  http: ^0.12.1
  pedometer: ^1.2.0
  percent_indicator: ^1.0.14
  flutter_launcher_icons: ^0.7.0
  path_provider:
  dio: ^3.0.9
  shared_preferences: ^0.5.7+3
  rflutter_alert: ^1.0.3
  firebase_auth:
  firebase_database:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "assets/icon/step.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
  - Logo.png
  - img-illustration1.png
  - Indicator.png
  - icon-show.png
  - PlayBtn.png
  - RIP.png
  - Sub3.png
  - Sub4.png
  - Sub5.png
  - Workout1.png
  - Workout2.png
  - Workout3.png
  - Down.png
  - chicken.png
  - carrot.png
  - lettuce.png
  - nam.png
  - ex1.png
  - ex2.png
  - ex3.png
  - ex4.png
  - playbtn2.png
  - addicon.png
  - iconper.png
  - iconif.png
  - video.png
  - iftime.png
  - clock.png
  - food.png
  - user.png
  - fires.png
  - barchart.png
  - girlexcer.png
  - zone1.png
  - zone.png
  - foodimg.png
  - heart.png
  - bookmark.png
  - share.png
  - calendar.png
  - Ellipse340.png
  - Bodymass.png
  - Body.png
  - Shape.png
  - Graph.png
  - archive.png
  - next.png
  - life.png
  - settings.png
  - star.png
  - instagram.png
  - back.png
  - fire.png
  - step.png
  - street.png
  - walk.jpg
  - run.jpg
  - shoes.png
  - hinhgym.jpg
  - Group.png
  - ic_mail.png
  - ic_phone.png
  - ic_lock.png
  - ic_user.png
  - break.jpeg
  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
